import "server-only";

export const apiRoutes = {
  event: "/event",
  eventById: (id: string) => `/event/${id}`,
  eventCategoryById: (id: string) => `/admin/category/${id}`,
  updateCategoryStatus: (id: string) => `/admin/category/${id}`,
  latestEvent: "/event/latest",
  latestCapacity: "/event/latest-capacity",
  contact: "/contact",
  booking: "/booking/create-ticket",
  feedback: "/feedback",
  subscribe: "/subscriber",
  preSignedUrl: "/admin/presign-url",
  getAllBookingTypes: "/admin/getall-bookingtype",
  getAllArtists: "/artist/all",
  getAllSponsors: "/sponsor/get-all",
  getAllVenues: "/venue/all-venue",
  getAllEventCategories: "/admin/category",
  getAllEvent: "/event/all-event",
  addEventCategory: "/admin/add-category",
  venueById: (id: string) => `/venue/${id}`,
  addVenue: "/venue",
  updateVenueStatus: (id: string) => `/venue/${id}/status`,
};
