export const routes = {
  home: "/",
  event: "/event",
  about: "/about",
  contact: "/contact",
  sponsors: "/sponsors",
  feedback: "/feedback",
  booking: "/booking",
  blog: "/blog",
  privacyPolicy: "/privacy-policy",
  termsAndConditions: "/terms-and-conditions",
  famousTemples: "/famous-temples",
  festivals: "/festivals",
  artist: "/artist",
  founder: "/founder",
  founders: "/founders",
};
