type SeoPage = {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  image?: string;
  noIndex?: boolean;
};

export const _seoConfig = {
  home: {
    path: "/",
    image: "/home_hero.webp",
    title: "Bharat Bhakti Sangam",
    description:
      "India’s most energetic devotional music experience where traditional bhajans, kirtans, and mantra chanting blend with modern beats and live performances.Book your Bhajan Clubbing tickets, join immersive spiritual EDM nights, and experience devotion like never before",
    keywords: [
      "bhajan clubbing",
      "bhajan",
      "kirtans",
      "mantra chanting",
      "bhajan clubbing tickets",
      "spiritual edm nights",
      "interactive kirtan sessions",
      "live devotional band performance",
      "electronic bhakti festivals",
      "bharat bhakti sangam gatherings",
      "bhajan clubbing concert",
      "kirtan event",
      "bhajan clubbing tickets booking",
      "devotional music experience",
      "kirtan concert in india",
      "modern bhajan jalsa night",
      "spiritual event contact",
      "bharat bhakti sangam gatherings",
      "bharat bhakti sangam contact",
      "bharat bhakti sangam",
      "bhakti",
      "bhajan clubbing concert",
      "electronic bhakti festivals",
      "interactive kirtan sessions",
      "kirtan concert in india",
    ],
  },
  about: {
    path: "/about",
    image: "/about_hero.webp",
    title: "About Bharat Bhakti Sangam",
    description:
      "Our mission is to create a new-age devotional experience where people can chant, celebrate, connect, and feel spiritual energy together through immersive bhajan clubbing concerts, interactive kirtan sessions, and modern bhakti music festivals across India.We aim to build a community where spirituality feels joyful, inclusive, and alive for everyone — especially the younger generation.",
    keywords: [
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
      "bhajan clubbing tickets booking",
      "bhajan clubbing tickets",
      "bhajan clubbing",
      "devotional music experience",
      "kirtan concert in india",
      "modern bhajan jalsa night",
      "spiritual event contact",
      "bharat bhakti sangam gatherings",
      "bharat bhakti sangam contact",
      "bharat bhakti sangam",
      "bhakti",
      "bhajan",
      "bhajan clubbing concert",
      "electronic bhakti festivals",
      "interactive kirtan sessions",
      "kirtan",
      "kirtan concert in india",
    ],
  },
  contact: {
    path: "/contact",
    image: "/contact_hero.webp",
    title: "Contact Bharat Bhakti Sangam",
    description:
      "Get in touch with Bharat Bhakti Sangam for event details, collaboration opportunities, and spiritual gathering inquiries.",
    keywords: [
      "contact bharat bhakti sangam",
      "event inquiry",
      "spiritual event contact",
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
      "bhajan clubbing tickets booking",
      "bhajan clubbing tickets",
      "bhajan clubbing",
      "devotional music experience",
      "kirtan concert in india",
      "modern bhajan jalsa night",
      "spiritual event contact",
      "bhajan clubbing tickets booking",
      "bhajan clubbing tickets",
      "bhajan clubbing",
      "devotional music experience",
    ],
  },
  event: {
    path: "/event",
    image: "/event.webp",
    title: "Latest Event",
    description:
      "Explore the latest devotional event from Bharat Bhakti Sangam.",
    keywords: [
      "bhajan clubbing",
      "devotional music experience",
      "kirtan concert in india",
      "modern bhajan jalsa night",
      "spiritual event contact",
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
      "bhajan clubbing tickets booking",
      "bhajan clubbing tickets",
      "devotional music experience",
    ],
  },
  booking: {
    path: "/booking",
    image: "/event.webp",
    title: "Event Booking",
    description: "Book tickets for the latest Bharat Bhakti Sangam event.",
    keywords: [
      "bhajan event booking",
      "bhajan booking",
      "event booking",
      "bhajan clubbing booking",
      "bhajan clubbing tickets booking",
      "bhajan clubbing tickets",
      "bhajan clubbing",
      "devotional music experience",
      "kirtan concert in india",
      "modern bhajan jalsa night",
      "spiritual event contact",
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
    ],
  },
  feedback: {
    path: "/feedback",
    image: "/feedback.webp",
    noIndex: true,
    title: "Event Feedback",
    description:
      "Share your feedback for the latest Bharat Bhakti Sangam event.",
    keywords: [
      "event feedback",
      "devotional event feedback",
      "spiritual event contact",
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
    ],
  },
  sponsors: {
    path: "/sponsors",
    noIndex: true,
    image: "/event.webp",
    title: "Sponsors",
    description:
      "Sponsorship information for Bharat Bhakti Sangam will be available soon.",
    keywords: [
      "bharat bhakti sangam sponsors",
      "event sponsorship",
      "spiritual event contact",
      "chant",
      "celebrate",
      "connect & feel spiritual energy together",
      "bhakti",
      "kirtan",
      "mantra chanting",
      "electronic bhakti",
      "live devotional band performances",
      "immersive devotional nightlife experiences",
      "bhajan clubbing concert",
      "kirtan event",
    ],
  },
  privacyPolicy: {
    path: "/privacy-policy",
    noIndex: true,
    image: "/policy_hero.webp",
    title: "Privacy Policy",
    description: "Privacy policy for Bharat Bhakti Sangam ",
    keywords: [
      "bharat bhakti sangam privacy policy",
      "event privacy policy",
      "spiritual event contact",
      "privacy policy",
      "data protection",
      "user data",
      "information security",
      "digital privacy",
      "online privacy",
      "personal data",
      "user privacy",
      "gdpr compliance",
      "data privacy",
      "cookie policy",
      "terms of service",
      "website privacy policy",
      "event privacy policy",
      "bhajan clubbing privacy policy",
      "devotional event privacy policy",
      "spiritual event privacy policy",
      "bharat bhakti sangam privacy policy",
    ],
  },
  termsAndConditions: {
    path: "/terms-and-conditions",
    noIndex: true,
    image: "/policy_hero.webp",
    title: "Terms and Conditions",
    description: "Terms and conditions for Bharat Bhakti Sangam",
    keywords: [
      "bharat bhakti sangam terms and conditions",
      "event terms and conditions",
      "spiritual event contact",
      "terms and conditions",
      "event rules",
      "user agreement",
      "website terms",
      "service terms",
      "booking terms",
      "ticket terms",
      "event policies",
      "organizer terms",
      "bhajan clubbing terms and conditions",
      "devotional event terms and conditions",
      "spiritual event terms and conditions",
      "bharat bhakti sangam terms and conditions",
    ],
  },
} satisfies Record<string, SeoPage>;

export type SeoPageKey = keyof typeof seoConfig;

export function getSeoKeywords(
  page: SeoPageKey,
  dynamicKeywords: string[] = [],
) {
  return [...seoConfig[page].keywords, ...dynamicKeywords];
}

export function getSeoPageConfig(
  page: SeoPageKey,
  overrides?: Partial<{
    path: string;
    image: string;
    noIndex: boolean;
    title: string;
    description: string;
    keywords: string[];
  }>,
) {
  return {
    ...seoConfig[page],
    ...overrides,
    keywords: overrides?.keywords ?? seoConfig[page].keywords,
  };
}

export const seoConfig: Record<string, SeoPage> = _seoConfig;
