type SeoPage = {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  image?: string;
  noIndex?: boolean;
};

export const _seoConfig = {
  home: {
    path: "/",
    image: "/home_hero.webp",
    title: "Bharat Bhakti Sangam",
    description:
      "India's most energetic devotional music experience where traditional bhajans, kirtans, and mantra chanting blend with modern beats and live performances. Book your Bhajan Clubbing tickets, join immersive spiritual EDM nights, and experience devotion like never before.",
    keywords: [
      " bhajan",
      " kirtans",
      " mantra chanting",
      " bhajan clubbing tickets",
      " spiritual edm nights",
      " interactive kirtan sessions",
      " live devotional band performance",
      " electronic bhakti festivals",
      " bharat bhakti sangam gatherings",
      " bhajan clubbing concert",
      " kirtan event",
      " bhajan clubbing tickets booking",
      " devotional music experience",
      " kirtan concert in india",
      " modern bhajan jalsa night",
      " spiritual event contact",
      " bharat bhakti sangam gatherings",
      " bharat bhakti sangam contact",
      " bharat bhakti sangam",
      " bhakti",
      " bhajan clubbing concert",
      " electronic bhakti festivals",
      " interactive kirtan sessions",
      " kirtan concert in india",
    ],
  },
  about: {
    path: "/about",
    image: "/about_hero.webp",
    title: "About Bharat Bhakti Sangam",
    description:
      "Our mission is to create a new-age devotional experience where people can chant, celebrate, connect, and feel spiritual energy together through immersive bhajan clubbing concerts, interactive kirtan sessions, and modern bhakti music festivals across India. We aim to build a community where spirituality feels joyful, inclusive, and alive for everyone, especially the younger generation.",
    keywords: [
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
      " bhajan clubbing tickets booking",
      " bhajan clubbing tickets",
      " bhajan clubbing",
      " devotional music experience",
      " kirtan concert in india",
      " modern bhajan jalsa night",
      " spiritual event contact",
      " bharat bhakti sangam gatherings",
      " bharat bhakti sangam contact",
      " bharat bhakti sangam",
      " bhakti",
      " bhajan",
      " bhajan clubbing concert",
      " electronic bhakti festivals",
      " interactive kirtan sessions",
      " kirtan",
      " kirtan concert in india",
    ],
  },
  contact: {
    path: "/contact",
    image: "/contact_hero.webp",
    title: "Contact Bharat Bhakti Sangam",
    description:
      "Get in touch with Bharat Bhakti Sangam for event details, collaboration opportunities, and spiritual gathering inquiries.",
    keywords: [
      " contact bharat bhakti sangam",
      " event inquiry",
      " spiritual event contact",
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
      " bhajan clubbing tickets booking",
      " bhajan clubbing tickets",
      " bhajan clubbing",
      " devotional music experience",
      " kirtan concert in india",
      " modern bhajan jalsa night",
      " spiritual event contact",
      " bhajan clubbing tickets booking",
      " bhajan clubbing tickets",
      " bhajan clubbing",
      " devotional music experience",
    ],
  },
  event: {
    path: "/event",
    image: "/event.webp",
    title: "Bharat Bhakti Sangam",
    description:
      "Explore the latest devotional event from Bharat Bhakti Sangam.",
    keywords: [
      " devotional music experience",
      " kirtan concert in india",
      " modern bhajan jalsa night",
      " spiritual event contact",
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
      " bhajan clubbing tickets booking",
      " bhajan clubbing tickets",
      " devotional music experience",
    ],
  },
  booking: {
    path: "/booking",
    image: "/event.webp",
    title: "Event Booking",
    description: "Book tickets for the latest Bharat Bhakti Sangam event.",
    keywords: [
      " bhajan event booking",
      " bhajan booking",
      " event booking",
      " bhajan clubbing booking",
      " bhajan clubbing tickets booking",
      " bhajan clubbing tickets",
      " bhajan clubbing",
      " devotional music experience",
      " kirtan concert in india",
      " modern bhajan jalsa night",
      " spiritual event contact",
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
    ],
  },
  feedback: {
    path: "/feedback",
    image: "/feedback.webp",
    title: "Event Feedback",
    description:
      "Share your feedback for the latest Bharat Bhakti Sangam event.",
    keywords: [
      " event feedback",
      " devotional event feedback",
      " spiritual event contact",
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
    ],
  },
  sponsors: {
    path: "/sponsors",
    image: "/event.webp",
    title: "Sponsors",
    description:
      "Sponsorship information for Bharat Bhakti Sangam will be available soon.",
    keywords: [
      " bharat bhakti sangam sponsors",
      " event sponsorship",
      " spiritual event contact",
      " chant",
      " celebrate",
      " connect & feel spiritual energy together",
      " bhakti",
      " kirtan",
      " mantra chanting",
      " electronic bhakti",
      " live devotional band performances",
      " immersive devotional nightlife experiences",
      " bhajan clubbing concert",
      " kirtan event",
    ],
  },
  privacyPolicy: {
    path: "/privacy-policy",
    image: "/policy_hero.webp",
    title: "Privacy Policy",
    description: "Privacy policy for Bharat Bhakti Sangam ",
    keywords: [
      " bharat bhakti sangam privacy policy",
      " event privacy policy",
      " spiritual event contact",
      " privacy policy",
      " data protection",
      " user data",
      " information security",
      " digital privacy",
      " online privacy",
      " personal data",
      " user privacy",
      " gdpr compliance",
      " data privacy",
      " cookie policy",
      " terms of service",
      " website privacy policy",
      " event privacy policy",
      " bhajan clubbing privacy policy",
      " devotional event privacy policy",
      " spiritual event privacy policy",
      " bharat bhakti sangam privacy policy",
    ],
  },
  termsAndConditions: {
    path: "/terms-and-conditions",
    image: "/policy_hero.webp",
    title: "Terms and Conditions",
    description: "Terms and conditions for Bharat Bhakti Sangam",
    keywords: [
      " bharat bhakti sangam terms and conditions",
      " event terms and conditions",
      " spiritual event contact",
      " terms and conditions",
      " event rules",
      " user agreement",
      " website terms",
      " service terms",
      " booking terms",
      " ticket terms",
      " event policies",
      " organizer terms",
      " bhajan clubbing terms and conditions",
      " devotional event terms and conditions",
      " spiritual event terms and conditions",
      " bharat bhakti sangam terms and conditions",
    ],
  },
  famousTemples: {
    path: "/famous-temples",
    image: "/og/famous-temples.jpg",
    title: "Famous Temples of India | Sacred Heritage Sites",
    description:
      "Explore India's most revered temples — Kedarnath, Badrinath, Tirupati Balaji, Meenakshi, and more. Timings, entry fees, and best time to visit.",
    keywords: [
      "Famous Temples of India",
      "Hindu Temples",
      "Kedarnath",
      "Badrinath",
      "Spiritual Sites",
      "Indian Heritage",
      "Tirupati Balaji",
      "Meenakshi Temple",
      "Vaishno Devi",
      "Shirdi Sai Baba",
      "Amarnath Yatra",
      "Golden Temple",
      "Sri Jagannath Puri",
      "Ramanathaswamy Temple",
      "Badrinath Yatra",
      "Kedarnath Yatra",
      "Vaishno Devi Yatra",
      "Shirdi Sai Baba Yatra",
      "Amarnath Yatra",
      "Golden Temple Yatra",
      "Sri Jagannath Puri Yatra",
      "Ramanathaswamy Temple Yatra",
    ],
  },
  blog: {
    path: "/blog",
    image: "/ogDefault.png",
    title: "Blog | Bhakti, Culture and Devotional Stories",
    description:
      "Read Bharat Bhakti Sangam articles on bhakti, devotional music, spiritual events, temple culture, and India's living devotional traditions.",
    keywords: [
      "Bharat Bhakti Sangam blog",
      "bhakti articles",
      "devotional music blog",
      "spiritual event stories",
      "kirtan articles",
      "bhajan blog",
      "Indian devotional culture",
      "temple culture",
      "spiritual gatherings",
    ],
  },
  influencer: {
    path: "/influencer",
    image: "/ogDefault.png",
    title: "Become an Official Influencer | Bharat Bhakti Sangam",
    description:
      "Join Bharat Bhakti Sangam as an official influencer and be a part of a spiritual movement. Share devotion, culture and tradition with millions of hearts.",
    keywords: [
      "Bharat Bhakti Sangam influencer",
      "devotional influencer collaboration",
      "spiritual content creator",
      "bhakti influencer program",
      "kirtan creator partnership",
      "bhajan clubbing influencer",
    ],
  },
} satisfies Record<string, SeoPage>;

export type SeoPageKey = keyof typeof seoConfig;

export function getSeoKeywords(
  page: SeoPageKey,
  dynamicKeywords: string[] = [],
) {
  return [...seoConfig[page].keywords, ...dynamicKeywords];
}

export function getSeoPageConfig(
  page: SeoPageKey,
  overrides?: Partial<{
    path: string;
    image: string;
    noIndex: boolean;
    title: string;
    description: string;
    keywords: string[];
  }>,
) {
  return {
    ...seoConfig[page],
    ...overrides,
    keywords: overrides?.keywords ?? seoConfig[page].keywords,
  };
}

export const seoConfig: Record<string, SeoPage> = _seoConfig;
