import {
  SanatanaHeroData,
  SanatanaEpochFilter,
  EpochSectionData,
} from "../types/sanatana.types";

export const SANATANA_HERO_DATA: SanatanaHeroData = {
  bannerSubtitle: "ANCIENT WISDOM • TIMELESS TRUTH",
  sanskritMantra: "धर्मो रक्षति रक्षितः • सत्यमेव जयते",
  heading: "SANĀTANA DHARMA",
  subheading: "A Chronological Odyssey Through Cosmic Ages & Divine Manifestations",
  description:
    "Embark on an illuminating pilgrimage across cosmic time cycles (Chaturyuga). From the primordial cosmic vibration of Hiranyagarbha to the heroic epics and contemporary global devotional revival, witness the unbroken continuum of eternal truth, righteous living, and pure Bhakti.",
  primaryCtaText: "Explore The Timeline",
  secondaryCtaText: "Vedic Principles",
  sacredSymbolImage: "/mandala.webp",
  stats: [
    {
      value: "4.32 Billion",
      label: "Years in a Kalpa",
      sublabel: "Cosmic Day of Brahma",
    },
    {
      value: "4 Sacred Yugas",
      label: "Cycles of Dharma",
      sublabel: "Satya • Treta • Dvapara • Kali",
    },
    {
      value: "10 Avatars",
      label: "Dashavatara Manifestations",
      sublabel: "Preserving Universal Balance",
    },
  ],
};

export const SANATANA_FILTERS: SanatanaEpochFilter[] = [
  { id: "all", label: "All Eras", sanskritLabel: "समस्त काल" },
  { id: "cosmic-origin", label: "Cosmic Dawn", sanskritLabel: "सृष्टि उत्पत्ति" },
  { id: "satya-yuga", label: "Satya Yuga", sanskritLabel: "सत्य युग" },
  { id: "treta-yuga", label: "Treta Yuga", sanskritLabel: "त्रेता युग" },
  { id: "dvapara-yuga", label: "Dvapara Yuga", sanskritLabel: "द्वापर युग" },
  { id: "kali-yuga", label: "Kali Yuga", sanskritLabel: "कलि युग" },
  { id: "modern-revival", label: "Modern Bhakti", sanskritLabel: "भक्ति पुनर्जागरण" },
];

export const SANATANA_EPOCHS_DATA: EpochSectionData[] = [
  {
    id: "cosmic-origin",
    title: "Cosmic Origins & Vedic Dawn",
    sanskritTitle: "सृष्टि आरम्भ एवं सनातन मूल",
    durationLabel: "Timeless Cosmic Continuum",
    themeColor: "#D4AF37",
    badgeBg: "bg-[#FFF9E6]",
    badgeBorder: "border-[#D4AF37]",
    description:
      "Before material creation, the unmanifest Supreme Consciousness (Brahman) resonated with the primordial primordial sound Om (AUM), birthing cosmic order (Rita) and the eternal vibrations of the four Vedas.",
    nodes: [
      {
        id: "cosmic-1",
        epochId: "cosmic-origin",
        order: 1,
        title: "Hiranyagarbha & Primordial Sound",
        sanskritTitle: "हिरण्यगर्भ एवं नादब्रह्म",
        periodBadge: "Cosmic Dawn",
        category: "Cosmology",
        description:
          "The golden womb of creation radiates from pure consciousness. The sacred syllable AUM echoes across infinity, establishing the energetic blueprint of all planetary systems, elements, and conscious life.",
        scriptureQuote: {
          verse: "हिरण्यगर्भः समवर्तताग्रे भूतस्य जातः पतिरेक आसीत्",
          source: "Rigveda 10.121.1",
        },
        keyPillars: ["Nada Brahma (Sound as God)", "Pancha Maha Bhutas", "Rita (Cosmic Order)"],
        imageUrl: "/about_mission.webp",
        imageAlt: "Cosmic Golden Womb and Divine Light",
        featuredDeityOrAvatar: "Brahman / Hiranyagarbha",
        significanceTag: "Origin of Universe",
      },
      {
        id: "cosmic-2",
        epochId: "cosmic-origin",
        order: 2,
        title: "Revelation of the Four Vedas",
        sanskritTitle: "श्रुति एवं चतुर्वेद प्राकट्य",
        periodBadge: "Vedic Antiquity",
        category: "Shruti Scriptures",
        description:
          "Enlightened Rishis meditating in the tranquil Himalayan valleys receive direct divine cognition (Shruti). The four monumental Vedas—Rig, Sama, Yajur, and Atharva—are remembered and transmitted with flawless oral precision.",
        scriptureQuote: {
          verse: "एकं सद्विप्रा बहुधा वदन्त्यग्निं यमं मातरिश्वानमाहुः",
          source: "Rigveda 1.164.46",
        },
        keyPillars: ["Rigveda (Hymns)", "Samaveda (Melodies)", "Yajurveda (Rituals)", "Atharvaveda (Sciences)"],
        imageUrl: "/mandala.webp",
        imageAlt: "Ancient Vedic Wisdom and Mandala",
        featuredDeityOrAvatar: "Saptarishis & Veda Vyasa",
        significanceTag: "Eternal Knowledge",
      },
    ],
  },
  {
    id: "satya-yuga",
    title: "Satya Yuga (Krita Yuga)",
    sanskritTitle: "सत्य युग • कृत युग",
    durationLabel: "1,728,000 Human Years",
    themeColor: "#C49A45",
    badgeBg: "bg-[#FFF7ED]",
    badgeBorder: "border-[#C49A45]",
    description:
      "The Golden Age of unblemished purity, truthfulness, and meditation. Dharma stood firmly on all four legs: Satya (Truth), Daya (Compassion), Tapas (Austerity), and Shaucha (Purity).",
    nodes: [
      {
        id: "satya-1",
        epochId: "satya-yuga",
        order: 3,
        title: "Matsya & Kurma Avataras",
        sanskritTitle: "मत्स्य एवं कूर्म अवतार",
        periodBadge: "Satya Yuga Dawn",
        category: "Divine Incarnation",
        description:
          "Lord Vishnu assumes the divine fish form to rescue King Manu, the sacred seeds of life, and the Vedas during the great deluge, followed by the cosmic churning (Samudra Manthana) yielding the nectar of immortality (Amrita).",
        scriptureQuote: {
          verse: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥",
          source: "Bhagavad Gita 4.7",
        },
        keyPillars: ["Dharma Preservation", "Samudra Manthana", "Amrita & Dhanvantari"],
        imageUrl: "/temples-images/kedarnath/kedarnath-hero.webp",
        imageAlt: "Sacred Himalayan Kedarnath shrine representing ancient tapasya",
        featuredDeityOrAvatar: "Matsya & Kurma Dev",
        significanceTag: "Preservation of Sanatana Life",
      },
      {
        id: "satya-2",
        epochId: "satya-yuga",
        order: 4,
        title: "Narasimha & Supreme Devotion of Prahlad",
        sanskritTitle: "नरसिंह अवतार एवं प्रह्लाद भक्ति",
        periodBadge: "Satya Yuga Peak",
        category: "Bhakti Triumph",
        description:
          "The fierce yet compassionate lion-man incarnation manifests from a pillar to protect young devotee Prahlad, proving that sincere surrender transcending fear and physical power is the ultimate refuge of the soul.",
        scriptureQuote: {
          verse: "सत्त्वं रजस्तम इति प्रकृतेर्गुणास्तैर्युक्तः परः पुरुष एक इहास्य धत्ते",
          source: "Srimad Bhagavatam 1.2.23",
        },
        keyPillars: ["Unshakable Bhakti", "Eradication of Tyranny", "Divine Omnipresence"],
        imageUrl: "/festivals/slider/image-2.webp",
        imageAlt: "Sacred fire and divine devotion depicting triumph of faith",
        featuredDeityOrAvatar: "Lord Narasimha & Bhakta Prahlad",
        significanceTag: "Eternal Protection of Devotees",
      },
    ],
  },
  {
    id: "treta-yuga",
    title: "Treta Yuga",
    sanskritTitle: "त्रेता युग",
    durationLabel: "1,296,000 Human Years",
    themeColor: "#E86A17",
    badgeBg: "bg-[#FFF2EB]",
    badgeBorder: "border-[#E86A17]",
    description:
      "The Silver Age characterized by the mastery of sacred sacrifices (Yajnas) and adherence to ethical duty. Dharma stood upon three legs as Lord Rama established Maryada Purushottam.",
    nodes: [
      {
        id: "treta-1",
        epochId: "treta-yuga",
        order: 5,
        title: "Vamana Avatara & Cosmic Humility",
        sanskritTitle: "वामन अवतार एवं बलि मोक्ष",
        periodBadge: "Treta Yuga Dawn",
        category: "Sacrifice & Surrender",
        description:
          "Lord Vishnu appears as a young ascetic Brahmin boy to measure the three worlds in three cosmic strides, humbling King Bali's pride while granting him celestial reign and eternal devotion.",
        scriptureQuote: {
          verse: "पद्भ्यां भूमिर्दिशः श्रोत्रात्तथा लोकाँ अकल्पयन्",
          source: "Purusha Suktam",
        },
        keyPillars: ["Total Surrender (Sharanagati)", "Subjugation of Ego", "Charity & Righteousness"],
        imageUrl: "/temples-images/tirupati-balaji/tirupati-balaji-hero.webp",
        imageAlt: "Sacred Tirupati Balaji Temple representing Lord Venkateswara",
        featuredDeityOrAvatar: "Lord Vamana Dev",
        significanceTag: "Cosmic Measure of Faith",
      },
      {
        id: "treta-2",
        epochId: "treta-yuga",
        order: 6,
        title: "Descent of Maryada Purushottam Shri Ram",
        sanskritTitle: "मर्यादा पुरुषोत्तम प्रभु श्री राम",
        periodBadge: "Treta Yuga Climax",
        category: "Epic Itihasa",
        description:
          "Lord Rama's life exemplifies flawless virtue, filial duty, unwavering promise (Raghukul Reeti), and the destruction of Ravana's ego. Ramrajya stands as the eternal archetype of enlightened governance.",
        scriptureQuote: {
          verse: "रघुकुल रीति सदा चलि आई। प्रान जाहुँ बरु बचनु न जाई॥",
          source: "Ramcharitmanas",
        },
        keyPillars: ["Ramrajya (Ideal Society)", "Bhakti of Hanuman", "Valmiki Ramayana"],
        imageUrl: "/temples-images/ayodhya/ayodhya-hero.webp",
        imageAlt: "Shri Ram Janmabhoomi Mandir Ayodhya",
        featuredDeityOrAvatar: "Lord Shri Ram & Mata Sita",
        significanceTag: "Apex of Righteous Living",
      },
    ],
  },
  {
    id: "dvapara-yuga",
    title: "Dvapara Yuga",
    sanskritTitle: "द्वापर युग",
    durationLabel: "864,000 Human Years",
    themeColor: "#740E0A",
    badgeBg: "bg-[#FDF2F2]",
    badgeBorder: "border-[#740E0A]",
    description:
      "The Bronze Age where Dharma rested upon two pillars: Truth and Compassion. Ritual worship, temple consecrations, and the supreme philosophy of Karma Yoga were bequeathed to humanity.",
    nodes: [
      {
        id: "dvapara-1",
        epochId: "dvapara-yuga",
        order: 7,
        title: "Leela of Yogeshwar Shri Krishna",
        sanskritTitle: "श्री कृष्ण लीला एवं बृज भक्ति",
        periodBadge: "Dvapara Yuga Peak",
        category: "Divine Ecstasy",
        description:
          "From the sweet pastoral melodies of Vrindavan's flute to the protection of devotees, Krishna's avatar demonstrates that supreme divinity is intimately loving, joyful, and accessible through heartfelt surrender.",
        scriptureQuote: {
          verse: "अधरं मधुरं वदनं मधुरं नयनं मधुरं हसितं मधुरम्। मधुराधिपतेरखिलं मधुरम्॥",
          source: "Madhurashtakam",
        },
        keyPillars: ["Rasa Leela & Pure Love", "Gita Upadesha", "Dharma Sthapana"],
        imageUrl: "/temples-images/banke-bihari/banke-bihari-hero.webp",
        imageAlt: "Banke Bihari Temple Vrindavan sacred altar",
        featuredDeityOrAvatar: "Bhagwan Shri Krishna & Radha Rani",
        significanceTag: "Eternal Melody of Devotion",
      },
      {
        id: "dvapara-2",
        epochId: "dvapara-yuga",
        order: 8,
        title: "The Song Celestial: Bhagavad Gita",
        sanskritTitle: "श्रीमद्भगवद्गीता ज्ञान",
        periodBadge: "Kurukshetra Revelation",
        category: "Universal Philosophy",
        description:
          "On the battlefield of Kurukshetra, Lord Krishna reveals 700 verses synthesizing Karma Yoga (selfless action), Jnana Yoga (transcendental wisdom), and Bhakti Yoga (unconditional love) for all generations of seekers.",
        scriptureQuote: {
          verse: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥",
          source: "Bhagavad Gita 2.47",
        },
        keyPillars: ["Nishkama Karma", "Universal Vishwaroopa", "Self-Realization"],
        imageUrl: "/temples-images/jagannath/jagannath-hero.webp",
        imageAlt: "Puri Jagannath Temple Lord of the Universe",
        featuredDeityOrAvatar: "Yogeshwar Krishna & Arjuna",
        significanceTag: "Universal Guidebook of Life",
      },
    ],
  },
  {
    id: "kali-yuga",
    title: "Kali Yuga",
    sanskritTitle: "कलि युग",
    durationLabel: "432,000 Human Years",
    themeColor: "#9A3412",
    badgeBg: "bg-[#FFF7ED]",
    badgeBorder: "border-[#9A3412]",
    description:
      "The Iron Age where Dharma stands upon a single pillar of Truth. In this era, supreme liberation and peace are attained most swiftly and joyfully through Nama Sankirtan—chanting the holy names of God.",
    nodes: [
      {
        id: "kali-1",
        epochId: "kali-yuga",
        order: 9,
        title: "Nama Sankirtan & The Bhakti Wave",
        sanskritTitle: "नाम संकीर्तन एवं भक्ति आन्दोलन",
        periodBadge: "Medieval Bhakti Era",
        category: "Devotional Wave",
        description:
          "Visionary saint-poets like Chaitanya Mahaprabhu, Meerabai, Sant Kabir, Surdas, and Tulsidas took the sacred chants into every village, demonstrating that love of God transcends caste, creed, and dogma.",
        scriptureQuote: {
          verse: "हरेर्नाम हरेर्नाम हरेर्नामैव केवलम्। कलौ नास्त्येव नास्त्येव नास्त्येव गतिरन्यथा॥",
          source: "Brihan-Naradiya Purana",
        },
        keyPillars: ["Harinaam Sankirtan", "Egalitarian Devotion", "Ecstatic Kirtan"],
        imageUrl: "/festivals/slider/image-1.webp",
        imageAlt: "Devotional gathering celebrating kirtan and joy",
        featuredDeityOrAvatar: "Chaitanya Mahaprabhu & Bhakti Saints",
        significanceTag: "Direct Path to Liberation",
      },
      {
        id: "kali-2",
        epochId: "kali-yuga",
        order: 10,
        title: "Advaita Revival & Adi Shankaracharya",
        sanskritTitle: "अद्वैत वेदान्त एवं चार धाम स्थापना",
        periodBadge: "Vedic Restoration",
        category: "Philosophical Synthesis",
        description:
          "Adi Shankaracharya traverses India from south to north, establishing four cardinal Mathas (Badrinath, Puri, Sringeri, Dwarka), consolidating monastic traditions, and re-establishing non-dual Vedic wisdom.",
        scriptureQuote: {
          verse: "ब्रह्म सत्यं जगन्मिथ्या जीवो ब्रह्मैव नापरः",
          source: "Vivekachudamani",
        },
        keyPillars: ["Advaita Vedanta", "Char Dham Consecration", "Panchayatana Puja"],
        imageUrl: "/temples-images/badrinath/badrinath-hero.webp",
        imageAlt: "Sacred Badrinath Temple in the Himalayas",
        featuredDeityOrAvatar: "Jagadguru Adi Shankaracharya",
        significanceTag: "Unification of Sanatana Traditions",
      },
    ],
  },
  {
    id: "modern-revival",
    title: "The Modern Sanatana Renaissance",
    sanskritTitle: "सनातन भक्ति पुनर्जागरण",
    durationLabel: "21st Century & Beyond",
    themeColor: "#740E0A",
    badgeBg: "bg-[#FFF9E6]",
    badgeBorder: "border-[#D4AF37]",
    description:
      "A global awakening where Vedic wisdom, conscious living, sacred clubbing, and youth-led devotional kirtan harmonize timeless spirituality with contemporary lifestyle.",
    nodes: [
      {
        id: "modern-1",
        epochId: "modern-revival",
        order: 11,
        title: "Bhajan Clubbing & Youth Awakening",
        sanskritTitle: "भजन क्लबिंग एवं युवा चेतना",
        periodBadge: "Contemporary Renaissance",
        category: "Spiritual Revolution",
        description:
          "Transforming modern social nightlife into high-vibration spiritual sanctuaries where millions of youth dance soberly, sing ancient mantras, and discover authentic inner peace through Bharat Bhakti Sangam.",
        scriptureQuote: {
          verse: "सङ्घे शक्तिः कलौ युगे — In Kali Yuga, supreme strength lies in righteous collective union.",
          source: "Subhashita",
        },
        keyPillars: ["Sober Celebrations", "High Frequency Chants", "Global Sanatana Community"],
        imageUrl: "/event.webp",
        imageAlt: "High energy Bhajan Clubbing spiritual event",
        featuredDeityOrAvatar: "Devotee Community & Youth Seekers",
        significanceTag: "Modern Devotional Movement",
      },
      {
        id: "modern-2",
        epochId: "modern-revival",
        order: 12,
        title: "Global Temple Resurgence & Eternal Future",
        sanskritTitle: "भव्य मन्दिर पुनरुत्थान एवं सार्वभौमिक प्रकाश",
        periodBadge: "Golden Future",
        category: "Eternal Continuum",
        description:
          "From monumental consecrated mandirs worldwide to digital archives preserving Vedic sciences, Sanātana Dharma continues its eternal promise: to guide every human heart towards self-realization, love, and universal harmony.",
        scriptureQuote: {
          verse: "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः। सर्वे भद्राणि पश्यन्तु मा कश्चिद्दुःखभाग्भवेत्॥",
          source: "Brihadaranyaka Upanishad",
        },
        keyPillars: ["Universal Well-being (Vasudhaiva Kutumbakam)", "Living Heritage", "Eternal Dharma"],
        imageUrl: "/temples-images/ayodhya/ayodhya-hero.webp",
        imageAlt: "Grand Temple Sanctum reflecting the eternal glory of Sanatana Dharma",
        featuredDeityOrAvatar: "Sanatana Parampara",
        significanceTag: "Vasudhaiva Kutumbakam",
      },
    ],
  },
];
