import { GalleryItem } from "./types";

export const DEFAULT_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "1",
    src: "/gallery/gallery_1.webp",
    imageUrl: "/gallery/gallery_1.webp",
    alt: "Sacred Temple River Reflection at Sunset",
    title: "Golden Hour Aarti at River Ghat",
    artistName: "Pt. Ramkishan & Vrindavan Choir",
    category: "Sacred Moments",
    location: "Varanasi Ghats, Uttar Pradesh",
    date: "Aug 2026",
    likes: 1842,
    commentsCount: 142,
  },
  {
    id: "2",
    src: "/gallery/gallery_2.webp",
    imageUrl: "/gallery/gallery_2.webp",
    alt: "Devotees gathering for Bhajan & Kirtan",
    title: "Devotional Kirtan Assembly",
    artistName: "Ananya Sharma & Bhakti Band",
    category: "Bhajan Clubbing",
    location: "Vrindavan, Uttar Pradesh",
    date: "Jul 2026",
    likes: 2450,
    commentsCount: 189,
  },
  {
    id: "3",
    src: "/gallery/gallery_3.webp",
    imageUrl: "/gallery/gallery_3.webp",
    alt: "Sacred Mahaprasad Offering with Steaming Aroma",
    title: "Divine Mahaprasad Offering",
    artistName: "Puri Temple Sevaks",
    category: "Prasad & Blessings",
    location: "Puri, Odisha",
    date: "Aug 2026",
    likes: 3120,
    commentsCount: 205,
  },
  {
    id: "4",
    src: "/festivals/holi/holi-1.webp",
    imageUrl: "/festivals/holi/holi-1.webp",
    alt: "Illuminated Ghat Aarti Celebration",
    title: "Illuminated Evening Ganga Aarti",
    artistName: "Haridwar Ved Pathshala",
    category: "Sacred Moments",
    location: "Haridwar, Uttarakhand",
    date: "Jun 2026",
    likes: 1980,
    commentsCount: 96,
  },
  {
    id: "5",
    src: "/about_mission.webp",
    imageUrl: "/about_mission.webp",
    alt: "Traditional Musicians playing Harmonium and Tabla",
    title: "Classical Ragas & Devotional Chants",
    artistName: "Ustad Zakir & Traditional Folk Troupe",
    category: "Kirtan Artists",
    location: "Mathura, Uttar Pradesh",
    date: "Jul 2026",
    likes: 1540,
    commentsCount: 78,
  },
  {
    id: "6",
    src: "/event.webp",
    imageUrl: "/event.webp",
    alt: "Traditional Pooja Thali with Diya and Incense",
    title: "Sacred Puja Thali & Diya",
    artistName: "Ayodhya Sanskriti Sangam",
    category: "Pooja Heritage",
    location: "Ayodhya, Uttar Pradesh",
    date: "Aug 2026",
    likes: 2890,
    commentsCount: 164,
  },
];
